nodeLinker: node-modules

npmAlwaysAuth: true
enableStrictSsl: false

npmAuthIdent: 'msazure:${AZURE_DEVOPS_PAT}'

npmRegistryServer: 'https://msazure.pkgs.visualstudio.com/_packaging/KustoWebExplorer/npm/registry/'

yarnPath: .yarn/releases/yarn-3.5.1.cjs
